services:
  - type: web
    name: texa-whatsapp-bot
    runtime: python
    plan: free
    region: oregon
    healthCheckPath: /ping
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
